#!/usr/bin/env python3
import sqlite3 as sql
import os, sys
from os.path import expanduser
LOCATION = '/Users/Peter/repos/imessage/settings.txt'
def set_group():
    #get home location
    db = sql.connect('/Users/Peter/Library/Messages/chat.db')
    cur = db.cursor()
    #retrieve id + group names
    cur.execute("SELECT guid, display_name FROM chat WHERE display_name IS NOT ''")
    rows = cur.fetchall()
    for i in range(len(rows)):
        print('{:02d} : {}'.format(i+1,rows[i][1]))
    x = int(input('select your group > '))
    groupid = rows[x - 1][0]
if len(sys.argv) == 2:
    what, who, where = sys.argv[1].split('|~|')
    os.system('/Users/Peter/repos/imessage/SendText.applescript "{} - \'{}\' " "{}"'.format(what,who,where))


